os:
  - osx
  - linux

services:
  - docker

language: generic

before_install:
  - packages/travis/travis.sh before_install

script:
  - packages/travis/travis.sh script

notifications:
  irc: "irc.rusnet.org.ru#ada-commits"

deploy:
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = linux"
  provider: bintray
  file: packages/travis/bintray.json
  user: reznikmm
  key:
    secure: "JnSA9QuGjOFZiVK94gYpoRLoWIxmohHrkWM1XIJimPYNuTe8WDg4ySREcddMLhABEW5J/hwx0/Fgi0pApsqKp4XtL8hcheqi7XU4X74aPplPfsKdfCIoYHAjaiWKh21jOyriRhkUEt7NECS0Z2aupngUG+c9X/TVfL5emKW4nLdsg+y+HaI9EDBGYDNfSm/6v7DasqRrsj9VpyIJdL/AUIlqw/OqR+Bpn/nUB2ql6c4YI4gNaFf+b5Z90hJ9QDjmJR45mi4UyoVTminZ0wW5dTpgRYInmlPeEytNJ0C04udUYqMKRyEzmy+euFd7FUti26JWG+2phGvAKb+AUnuNnr5d8xt6iLChkgTiDrMRjJk/z+a2+4AzkUBQEPt8cIuf6y7TqxHEokBa2aey8wHUFITSCleIR+2ss9VL/JTNcLEKAul5gzw3WDx4wJcWqrWmRbwCU1NexQwMxcKKnFXjoOz0FyTq0svWlY5QAbj5ukvhLGqxFPyvT78+RpZ4kOIO0eg/GMgjhpu+yq6YEn/ECOT8V0H3r4O/RbyRbcTi/UIdkW3VEQeg0idU3xQ8SEOLSSyi3ZXMDK99e/BYV99WL8b4Y4KwMp98rywt6Zz78sYjWUqE3+ZVmVo0LbJFnI/LI+5F5RGvpuvu63Hvg/esaSAGqahPgyKQdyTrcVjMN6U="
