os:
  - linux

sudo: required
dist: trusty
language: generic

services:

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade
  - sudo apt-get install update-manager-core
  - sudo do-release-upgrade -f DistUpgradeViewNonInteractive
  - sudo apt-get install gnat gprbuild make

script:
  - gnatmake --version
  - gprbuild --version
  - make
  - make check
