os:
  - osx
  - linux

services:
  - docker

language: generic

before_install:
  - packages/travis/travis.sh before_install

script:
  - packages/travis/travis.sh script

notifications:
  irc: "irc.rusnet.org.ru#ada"

