os:
  - osx
  - linux

services:
  - docker

language: generic

before_install:
  - packages/travis/travis.sh before_install

script:
  - packages/travis/travis.sh script

notifications:
  irc: "irc.rusnet.org.ru#ada-commits"

deploy:
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = linux"
  provider: bintray
  file: packages/travis/bintray.json
  user: reznikmm
  key:
    secure: OTWn4PhHwRcTTXQ41zuuQ8LGncuhrdGpYk7kza+Ihf4cQW1yaNVCUSS8YxeAHNVN9MYOSwjbDxYtaNLoUBUI8cjCXTnxU2P/vGL19dkHPZlwu4Oa86zYb45vXr5HIoqUnNId+Qie4OH+iUyfvZrgzfdG0JHAB9RMTgVxu1vKZUKAa8a9VKq7lK9yIQKkleOYNiR7u7zD9JYnNGMB9A1xzNdsrH19kGHfdA3lfyiU2scb8H2cCkOzf8Y2EOPI0JXdPORaOY8I/tYVRbr4lwHCx3jzIiwOXY4a2fsbZpjtD1yLobxQYUK5QB58THB5UXdVdAOxoRvcIjqzAL5F0BFuj+rPteoVmwKOu4wbLJlrcqg2wAlNTOafrx2igpndmXwTC8hhb5rMX5i3TRkI/ZLk43fYHpH05pa3lbrrgRLuYsbBghus80g9xTzMg3Hs2MhuvzO2n3VhQ+FcuycVSIf7jMFqqfWrigAfaAsKSldvIkYW27Skw/atlLPnbddRz2dmSLRuaFrhH+C6X4qYjq1gIAZZP1x9Dh9dyYmeTcq+dx4AhAEw8d5bb/yIRe+zU1ZM4H7qUFUr3DLrhSGXKMAp+9JXBHxrzRQDNEfmIusXzUSuo+0k2u7DmeCH8eoUbnagx4VsRI+0yfXM9SGBu1j1XSJaVk3ltRXO3en61ZU9pwI=
