os:
  - osx

language: generic

before_install:
  - export NODE_PATH=$(npm config get prefix)/lib/node_modules
  - npm -g install requirejs
  - npm -g install js-beautify
  - export OSX_GCC=gcc-5.2.0-x86_64-apple-darwin15-bin
  - export URL=http://sourceforge.net/projects/gnuada/files
  - wget $URL/'GNAT_GCC%20Mac%20OS%20X/5.2.0/native'/$OSX_GCC.tar.bz2
  - tar xjf $OSX_GCC.tar.bz2
  - cd $OSX_GCC; echo -e "\n$HOME/gnat\ny\ny\n" | ./doinstall
  - export PATH=$HOME/gnat/bin:$PATH
  - cd $TRAVIS_BUILD_DIR

script:
  - gnatls -v
  - make config && ./configure --disable-amf && make
  - make check

notifications:
  irc: "irc.rusnet.org.ru#ada"

