os:
  - osx

language: generic

services:

before_install:
  - export OSX_GCC=gcc-5.1.0-x86_64-apple-darwin13-2015-bin
  - export URL=http://sourceforge.net/projects/gnuada/files
  - wget $URL/'GNAT_GCC%20Mac%20OS%20X/5.1.0/native-2015'/$OSX_GCC.tar.bz2
  - tar xjf $OSX_GCC.tar.bz2
  - cd $OSX_GCC; echo -e "\n$HOME/gnat\ny\ny\n" | ./doinstall
  - export PATH=$HOME/gnat/bin:$PATH
  - cd $TRAVIS_BUILD_DIR

script:
  - gnatls -v
  - make
  - make check
